# Generated by Django 3.1.7 on 2021-02-20 22:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Node',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Link',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=200)),
                ('node_from', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='node_from', to='diagram.node')),
                ('node_to', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='node_to', to='diagram.node')),
            ],
        ),
    ]
