# Generated by Django 3.1.7 on 2021-02-22 07:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('diagram', '0002_link_arrorws'),
    ]

    operations = [
        migrations.RenameField(
            model_name='link',
            old_name='arrorws',
            new_name='arrows',
        ),
    ]
